apiVersion: batch/v1
kind: Job
metadata:
  name: ml-train-job
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: quay.io/techinea/ml-trainer:train-latest
        args: ["--mode", "train", "--mlflow-uri", "http://mlflow-server:5000"]
        volumeMounts:
          - name: dataset-pvc
            mountPath: /data
          - name: output-pvc
            mountPath: /output
      restartPolicy: Never
      volumes:
        - name: dataset-pvc
          persistentVolumeClaim:
            claimName: dataset-pvc
        - name: output-pvc
          persistentVolumeClaim:
            claimName: output-pvc
