apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-server.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "model-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "model-server.name" . }}
    spec:
      containers:
      - name: model-server
        image: "quay.io/{{ .Values.quayNamespace }}/ml-trainer:serve-latest"
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: {{ .Values.mlflowUri | quote }}
