
apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelserver.fullname" . }}
spec:
  selector:
    app: {{ include "modelserver.name" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
