name: Build and Push Docker image to Quay.io

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push train image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.train
        push: true
        tags: quay.io/${{ secrets.QUAY_NAMESPACE }}/ml-trainer:train-latest

    - name: Build and push serve image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.serve
        push: true
        tags: quay.io/${{ secrets.QUAY_NAMESPACE }}/ml-trainer:serve-latest
