
name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unit tests
      run: python3 scripts/test_script.py
    - name: Run training
      env:
        MLFLOW_TRACKING_URI: http://mlflow.techinea.svc.cluster.local:5000
      run: bash scripts/run_train.sh
