
name: CD Deploy

on:
  push:
    paths:
      - 'scripts/serve.py'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy to OpenShift
      run: |
        echo "Triggering deployment to OpenShift"
        # You can customize oc commands or ArgoCD CLI here
